# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  nuget-org:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
  sherweb:
    type: nuget-feed
    url: https://nuget.pkg.github.com/Sherweb/index.json
    username: op-github-svc
    password: ${{secrets.OP_GITHUB_SVC_PAT}}
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/" # Location of package manifests
    registries:
      - nuget-org
      - sherweb
    schedule:
      interval: "daily"
      time: "00:00"