changelog:
  categories:
    - title: Breaking changes
      labels:
        - breaking change
    - title: Features
      labels:
        - feature
    - title: Changes
      labels:
        - change
    - title: Fixes
      labels:
        - bug
