parameters:
  - name: arrayExecs
    type: object
    default:
      - none
  - name: arrayPackages
    type: object
    default:
      - Mongo.Migration
  - name: dockerfilePath
    type: string
    default: "none"
  - name: dotNetSdkVersion
    type: string
    default: '8.x'
  - name: gitRepoName
    type: string
    default: "Mongo.Migration"

variables:
  - group: github-credentials

pr:
  - main
  - master
trigger: none

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: tools
      type: git
      name: OfficeProtect/tools
      ref: main

stages:
  - stage: PR_Analysis
    displayName: Lint, Tests and Static Analysis
    jobs:
      - template: azdoTemplates/workflows/pr-dotnet.yaml@tools
        parameters:
          arrayExecs: ${{ parameters.arrayExecs }}
          arrayPackages: ${{ parameters.arrayPackages }}
          dockerfilePath: "${{ parameters.dockerfilePath }}"
          dotNetSdkVersion: "${{ parameters.dotNetSdkVersion }}"
          projectPath: "$(System.DefaultWorkingDirectory)/${{ parameters.gitRepoName }}"
