parameters:
  - name: arrayExecs
    type: object
    default:
      - none
  - name: arrayPackages
    type: object
    default:
      - Mongo.Migration
  - name: dotNetSdkVersion
    type: string
    default: '8.x'
  - name: gitRepoName
    type: string
    default: "Mongo.Migration"

variables:
  - group: DatadogCI
  - group: github-credentials

trigger: none

schedules:
  - cron: "0 4 * * 1-5"
    displayName: Daily Test Coverage
    branches:
      include:
        - main
        - master
    always: false

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: tools
      type: git
      name: OfficeProtect/tools
      ref: main
    - repository: kube-services
      type: github
      endpoint: op-github-svc
      name: sherweb/kube-services
      ref: dev

stages:
  - stage: TestCoverage
    displayName: DotNet Test Coverage
    jobs:
      - template: azdoTemplates/workflows/test-coverage-dotnet.yaml@tools
        parameters:
          arrayExecs: ${{ parameters.arrayExecs }}
          arrayPackages: ${{ parameters.arrayPackages }}
          dotNetSdkVersion: "${{ parameters.dotNetSdkVersion }}"
          projectPath: "$(System.DefaultWorkingDirectory)/${{ parameters.gitRepoName }}"
          gitRepoName: "${{ parameters.gitRepoName }}"
